/**
 * DO NOT EDIT THIS FILE
 */

import { Game } from "./Game";

const game = new Game();

const info = document.getElementById("info");
const button = document.getElementById("play-button");
const board = document.getElementById("board");
const x = document.getElementById("X");
const o = document.getElementById("O");

button.addEventListener("click", () => {
  game.restart();
  draw(game);
});
const draw = (game: Game) => {
  board.innerHTML = "";

  game.getCells().forEach((cell, i) => {
    const div = document.createElement("div");
    div.className = `box${i}`;
    if (cell !== "-") {
      div.innerText = cell;
    }
    div.addEventListener("click", () => {
      game.onClick(i);
      draw(game);
    });
    board.appendChild(div);
  });

  if (game.isTie()) {
    info.innerText = `It's a tie!`;
    button.removeAttribute("disabled");
    button.className = "button button-hoverable";
  } else if (game.getWinner() !== "-") {
    info.className = "tracking-out-contract";
    setInterval(function() {
      info.innerText = `Nice, ${game.getWinner()} won!`;
    }, 1000);
    setInterval(function() {
      info.className = "tracking-in-expand";
    }, 1000);

    button.removeAttribute("disabled");
    button.className = "btn striped-shadow white";
  } else {
    button.setAttribute("disabled", "true");
    button.className = "btn striped-shadow white";
    x.className = game.getTurn() === "X" ? "text-flicker-in-glow" : "";
    o.className = game.getTurn() === "O" ? "text-flicker-in-glow" : "";
  }
};

draw(game);
